[package]
name = "restaraunt"
version = "0.1.0"
edition = "2021"
rust-version = "1.66.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-modules = "0.6"
